### ISSUE TITLE
Adding box to boxlist via !box yes causes errors

### ISSUE THREAD

**Issue by simonthezhao** [ayylmar/box#3]
After opening a box and you get a prompt in chat to add the box to your list of boxes via either !box yes or !box no, if you type in yes proxy will throw the following error once every ~5 seconds. Boxlist.json is also not updated.

`failed to write the boxlist config TypeError: path must be a string or Buffer
    at Object.fs.openSync (fs.js:663:18)
    at fs.writeFileSync (fs.js:1314:33)
    at Timeout.save [as _onTimeout] (D:\TERA\tools\tera-proxy\bin\node_modules\box\utils.js:23:5)
    at ontimeout (timers.js:460:13)
    at tryOnTimeout (timers.js:296:5)
    at Timer.listOnTimeout (timers.js:259:5)`

**Comment by ayylmar** [comment]
Fix't
